# Generated by Django 2.2.20 on 2021-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0002_auto_20210424_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
