# Generated by Django 2.2.20 on 2021-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0003_auto_20210424_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
