# Generated by Django 2.2.20 on 2021-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0004_auto_20210424_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
