# Generated by Django 2.2.20 on 2021-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0005_auto_20210424_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
