# Generated by Django 2.2.20 on 2021-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0006_menu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
